#!/bin/bash
# Hook: Blocks git commits that contain AI attribution.
# CLAUDE.md rule: "NEVER add AI attribution to commits, comments, PRs"

set -euo pipefail

INPUT=$(cat)
COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty')

# Only validate on git commit commands
if ! echo "$COMMAND" | grep -q "git commit"; then
  exit 0
fi

# Check for AI attribution patterns in the commit command
if echo "$COMMAND" | grep -qi "Co-Authored-By.*Claude\|Generated with Claude\|Generated by Claude\|Claude Code\|noreply@anthropic"; then
  cat >&2 <<EOF
BLOCKED: Commit contains AI attribution.
Per CLAUDE.md, contributions must appear as solely from the user.
Remove any Co-Authored-By, "Generated with Claude Code", or similar attribution.
EOF
  exit 2
fi

exit 0
