#!/bin/bash
# Hook: Blocks git commits that contain AI attribution.
# CLAUDE.md rule: "NEVER add AI attribution to commits, comments, PRs"
#
# Patterns are anchored to actual attribution constructs (trailers, generation
# stamps, the Anthropic noreply email, the robot emoji boilerplate). Bare
# mentions of "Claude" or "Claude Code" in technical prose do NOT trigger —
# describing the harness behavior in a commit message body is fine.

set -euo pipefail

INPUT=$(cat)
COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty')

# Matches `git commit`, optionally with a `-C <path>` global option inserted
# before the subcommand (e.g. `git -C /some/worktree commit -m ...`).
QPATH='("[^"]*"|'"'"'[^'"'"']*'"'"'|[^[:space:]]+)'
GIT_COMMIT_RE="git([[:space:]]+-C[[:space:]]+${QPATH})?[[:space:]]+commit([[:space:]]|\$)"

# Only validate on git commit commands
if ! [[ "$COMMAND" =~ $GIT_COMMIT_RE ]]; then
  exit 0
fi

# Attribution patterns. Each MUST be specific to attribution context — bare
# product references in technical prose are fine.
#
# - Co-Authored-By: <anything> Claude  (or @anthropic email) → trailer attribution
# - Generated with Claude Code         → Claude Code's default boilerplate
# - Generated by Claude                → variant
# - noreply@anthropic                  → Anthropic's commit email always means attribution
# - 🤖 Generated / 🤖 Co-Authored      → robot emoji + generation/auth stamp
ATTRIBUTION_RE='Co-Authored-By:.*(Claude|@anthropic)'
ATTRIBUTION_RE+='|Generated with Claude Code'
ATTRIBUTION_RE+='|Generated by Claude'
ATTRIBUTION_RE+='|noreply@anthropic'
ATTRIBUTION_RE+='|🤖 Generated'
ATTRIBUTION_RE+='|🤖 Co-Authored'

if echo "$COMMAND" | grep -qiE "$ATTRIBUTION_RE"; then
  cat >&2 <<EOF
BLOCKED: Commit contains AI attribution.
Per CLAUDE.md, contributions must appear as solely from the user.
Remove any Co-Authored-By, "Generated with Claude Code", or similar attribution.
EOF
  exit 2
fi

exit 0
