/**
 * Stats command
 * Compute and display contribution statistics.
 */

import { getStateManager } from '../core/index.js';
import { computeContributionStats } from '../core/stats.js';
import type { StatsOutput } from '../formatters/json.js';

export async function runStats(): Promise<StatsOutput> {
  const stateManager = getStateManager();
  const state = stateManager.getState();
  const activePRCount = state.lastDigest?.summary?.totalActivePRs ?? 0;

  const stats = computeContributionStats({
    repoScores: state.repoScores ?? {},
    activePRCount,
  });

  return {
    ...stats,
    mergeRateFormatted: `${(stats.mergeRate * 100).toFixed(1)}%`,
    username: state.config.githubUsername,
  };
}

export function formatStatsMarkdown(stats: StatsOutput): string {
  const lines: string[] = [
    `# OSS Contribution Stats for @${stats.username}`,
    '',
    '| Metric | Value |',
    '|--------|-------|',
    `| Merged PRs | ${stats.totalMerged} |`,
    `| Merge Rate | ${stats.mergeRateFormatted} |`,
    `| Active PRs | ${stats.activePRs} |`,
    `| Repos Contributed | ${stats.reposContributed} |`,
    '',
  ];

  if (stats.topRepos.length > 0) {
    lines.push('## Top Repos', '', '| Repo | Merged PRs |', '|------|-----------|');
    for (const repo of stats.topRepos) {
      lines.push(`| ${repo.repo} | ${repo.mergedCount} |`);
    }
    lines.push('');
  }

  lines.push('---', '*Generated by [OSS Autopilot](https://github.com/costajohnt/oss-autopilot)*');
  return lines.join('\n');
}

interface BadgeData {
  schemaVersion: number;
  label: string;
  message: string;
  color: string;
}

function pickBadgeColor(stats: StatsOutput): string {
  if (stats.totalMerged === 0) return 'blue';
  if (stats.mergeRate >= 0.8) return 'brightgreen';
  if (stats.mergeRate >= 0.6) return 'green';
  if (stats.mergeRate >= 0.4) return 'yellow';
  return 'orange';
}

export function formatStatsBadge(stats: StatsOutput): BadgeData {
  const message =
    stats.totalMerged > 0 ? `${stats.mergeRateFormatted} merge rate | ${stats.totalMerged} merged` : 'Getting Started';

  return { schemaVersion: 1, label: 'OSS Contributions', message, color: pickBadgeColor(stats) };
}
