/**
 * Stats command
 * Compute and display contribution statistics.
 */

import { getStateManager } from '../core/index.js';
import { computeContributionStats } from '../core/stats.js';
import type { StatsOutput } from '../formatters/json.js';

export async function runStats(): Promise<StatsOutput> {
  const stateManager = getStateManager();
  const state = stateManager.getState();
  const activePRCount = state.lastDigest?.summary?.totalActivePRs ?? 0;

  const stats = computeContributionStats({
    repoScores: state.repoScores,
    activePRCount,
  });

  return {
    ...stats,
    mergeRateFormatted: `${(stats.mergeRate * 100).toFixed(1)}%`,
    username: state.config.githubUsername,
  };
}

export function formatStatsMarkdown(stats: StatsOutput): string {
  const lines: string[] = [
    `# OSS Contribution Stats for @${stats.username}`,
    '',
    '| Metric | Value |',
    '|--------|-------|',
    `| Merged PRs | ${stats.totalMerged} |`,
    `| Merge Rate | ${stats.mergeRateFormatted} |`,
    `| Active PRs | ${stats.activePRs} |`,
    `| Repos Contributed | ${stats.reposContributed} |`,
    '',
  ];

  if (stats.topRepos.length > 0) {
    lines.push('## Top Repos', '', '| Repo | Merged PRs |', '|------|-----------|');
    for (const repo of stats.topRepos) {
      lines.push(`| ${repo.repo} | ${repo.mergedCount} |`);
    }
    lines.push('');
  }

  lines.push('---', '*Generated by [OSS Autopilot](https://github.com/costajohnt/oss-autopilot)*');
  return lines.join('\n');
}

export function formatStatsBadge(stats: StatsOutput): object {
  const message =
    stats.totalMerged > 0 ? `${stats.mergeRateFormatted} merge rate | ${stats.totalMerged} merged` : 'Getting Started';

  const color =
    stats.mergeRate >= 0.8
      ? 'brightgreen'
      : stats.mergeRate >= 0.6
        ? 'green'
        : stats.mergeRate >= 0.4
          ? 'yellow'
          : stats.totalMerged === 0
            ? 'blue'
            : 'orange';

  return { schemaVersion: 1, label: 'OSS Contributions', message, color };
}
