/**
 * Tests for stats command
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

vi.mock('../core/index.js', () => ({
  getStateManager: vi.fn(),
}));

import { getStateManager } from '../core/index.js';
import { runStats, formatStatsMarkdown, formatStatsBadge } from './stats.js';
import type { StatsOutput } from '../formatters/json.js';

const mockGetStateManager = vi.mocked(getStateManager);

describe('runStats', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockGetStateManager.mockReturnValue({
      getState: vi.fn().mockReturnValue({
        repoScores: {
          'owner/repo-a': {
            repo: 'owner/repo-a',
            mergedPRCount: 5,
            closedWithoutMergeCount: 1,
          },
          'owner/repo-b': {
            repo: 'owner/repo-b',
            mergedPRCount: 3,
            closedWithoutMergeCount: 0,
          },
        },
        lastDigest: {
          summary: { totalActivePRs: 2 },
        },
        config: {
          githubUsername: 'testuser',
        },
      }),
    } as any);
  });

  it('should return stats data', async () => {
    const result = await runStats();

    expect(result.totalMerged).toBe(8);
    expect(result.totalClosed).toBe(1);
    expect(result.activePRs).toBe(2);
    expect(result.reposContributed).toBe(2);
    expect(result.username).toBe('testuser');
  });

  it('should format merge rate as percentage string', async () => {
    const result = await runStats();

    // 8 / (8 + 1) = 88.9%
    expect(result.mergeRateFormatted).toBe('88.9%');
  });

  it('should handle missing lastDigest gracefully', async () => {
    mockGetStateManager.mockReturnValue({
      getState: vi.fn().mockReturnValue({
        repoScores: {},
        lastDigest: undefined,
        config: { githubUsername: 'testuser' },
      }),
    } as any);

    const result = await runStats();

    expect(result.activePRs).toBe(0);
    expect(result.totalMerged).toBe(0);
  });
});

describe('formatStatsMarkdown', () => {
  const stats: StatsOutput = {
    totalMerged: 10,
    totalClosed: 2,
    mergeRate: 10 / 12,
    mergeRateFormatted: '83.3%',
    activePRs: 3,
    reposContributed: 4,
    topRepos: [
      { repo: 'owner/repo-a', mergedCount: 5 },
      { repo: 'owner/repo-b', mergedCount: 3 },
    ],
    username: 'testuser',
  };

  it('should generate valid markdown with heading and table', () => {
    const markdown = formatStatsMarkdown(stats);

    expect(markdown).toContain('# OSS Contribution Stats for @testuser');
    expect(markdown).toContain('| Merged PRs | 10 |');
    expect(markdown).toContain('| Merge Rate | 83.3% |');
    expect(markdown).toContain('| Active PRs | 3 |');
    expect(markdown).toContain('| Repos Contributed | 4 |');
  });

  it('should include OSS Autopilot attribution link', () => {
    const markdown = formatStatsMarkdown(stats);

    expect(markdown).toContain('*Generated by [OSS Autopilot](https://github.com/costajohnt/oss-autopilot)*');
  });

  it('should include top repos table', () => {
    const markdown = formatStatsMarkdown(stats);

    expect(markdown).toContain('## Top Repos');
    expect(markdown).toContain('| owner/repo-a | 5 |');
    expect(markdown).toContain('| owner/repo-b | 3 |');
  });
});

describe('formatStatsBadge', () => {
  it('should return brightgreen for merge rate >= 80%', () => {
    const badge = formatStatsBadge({
      totalMerged: 9,
      totalClosed: 1,
      mergeRate: 0.9,
      mergeRateFormatted: '90.0%',
      activePRs: 1,
      reposContributed: 2,
      topRepos: [],
      username: 'testuser',
    });

    expect(badge).toEqual(
      expect.objectContaining({
        schemaVersion: 1,
        label: 'OSS Contributions',
        color: 'brightgreen',
      }),
    );
    expect((badge as any).message).toContain('90.0%');
  });

  it('should return blue with "Getting Started" for 0 merged PRs', () => {
    const badge = formatStatsBadge({
      totalMerged: 0,
      totalClosed: 0,
      mergeRate: 0,
      mergeRateFormatted: '0.0%',
      activePRs: 0,
      reposContributed: 0,
      topRepos: [],
      username: 'testuser',
    });

    expect(badge).toEqual(
      expect.objectContaining({
        schemaVersion: 1,
        label: 'OSS Contributions',
        message: 'Getting Started',
        color: 'blue',
      }),
    );
  });

  it('should return orange for low merge rate (< 40%)', () => {
    const badge = formatStatsBadge({
      totalMerged: 1,
      totalClosed: 4,
      mergeRate: 0.2,
      mergeRateFormatted: '20.0%',
      activePRs: 0,
      reposContributed: 1,
      topRepos: [],
      username: 'testuser',
    });

    expect(badge).toEqual(
      expect.objectContaining({
        schemaVersion: 1,
        label: 'OSS Contributions',
        color: 'orange',
      }),
    );
  });

  it('should return green for merge rate between 60-79%', () => {
    const badge = formatStatsBadge({
      totalMerged: 7,
      totalClosed: 3,
      mergeRate: 0.7,
      mergeRateFormatted: '70.0%',
      activePRs: 1,
      reposContributed: 2,
      topRepos: [],
      username: 'testuser',
    });

    expect(badge).toEqual(expect.objectContaining({ color: 'green' }));
  });

  it('should return yellow for merge rate between 40-59%', () => {
    const badge = formatStatsBadge({
      totalMerged: 5,
      totalClosed: 5,
      mergeRate: 0.5,
      mergeRateFormatted: '50.0%',
      activePRs: 0,
      reposContributed: 1,
      topRepos: [],
      username: 'testuser',
    });

    expect(badge).toEqual(expect.objectContaining({ color: 'yellow' }));
  });
});
