#!/usr/bin/env bash
# Rebuild the @oss-autopilot/dashboard SPA if it's stale relative to source.
#
# Sibling to scripts/build-cli-if-stale.sh (#1292). Differs in two ways:
#
# 1. The dashboard depends on @oss-autopilot/core via the workspace:* protocol
#    (npm cannot resolve workspace:* dependencies), so this helper requires
#    pnpm and exits with a remediation hint when it's missing rather than
#    falling back to a build that would fail confusingly mid-stream.
#
# 2. The build runs core's tsc step before dashboard's vite build so the
#    dashboard's tsc has the freshest .d.ts types from core (the CLI bundle
#    step in build-cli-if-stale.sh runs esbuild, not tsc, so the .d.ts files
#    aren't regenerated by it).
#
# A bundle is "stale" when dist/index.html is missing OR when any of the
# following are newer than it:
#   packages/dashboard/src/**
#   packages/dashboard/package.json
#   packages/dashboard/vite.config.ts
#   packages/dashboard/tsconfig.json
#
# Editor swap files (.DS_Store, *~, *.swp, *.swo, .#*) and node_modules / .git
# trees are excluded so an editor leaving a temp file alongside src/ does not
# trigger a rebuild on every session.
#
# Exit codes:
#   0 — bundle is current; no rebuild attempted.
#   1 — bundle was rebuilt successfully.
#   2 — bundle is stale and the rebuild attempt FAILED. The remediation
#       command is printed to stdout for the caller to surface.
#   3 — invocation error (PLUGIN_ROOT missing, packages/dashboard not found).
#
# Usage:
#   build-dashboard-if-stale.sh <plugin-root>
#
# Or, equivalently, with $CLAUDE_PLUGIN_ROOT exported:
#   build-dashboard-if-stale.sh
#
# All build noise is sent to stderr; stdout stays clean for the caller.

set -uo pipefail

PLUGIN_ROOT="${1:-${CLAUDE_PLUGIN_ROOT:-}}"
if [ -z "${PLUGIN_ROOT}" ]; then
  echo "build-dashboard-if-stale.sh: missing plugin root (pass as arg or export CLAUDE_PLUGIN_ROOT)" >&2
  exit 3
fi
if [ ! -d "${PLUGIN_ROOT}/packages/dashboard" ]; then
  echo "build-dashboard-if-stale.sh: packages/dashboard not found under ${PLUGIN_ROOT}" >&2
  exit 3
fi

DASHBOARD_INDEX="${PLUGIN_ROOT}/packages/dashboard/dist/index.html"
DASHBOARD_PKG="${PLUGIN_ROOT}/packages/dashboard/package.json"
DASHBOARD_SRC="${PLUGIN_ROOT}/packages/dashboard/src"
VITE_CONFIG="${PLUGIN_ROOT}/packages/dashboard/vite.config.ts"
TS_CONFIG="${PLUGIN_ROOT}/packages/dashboard/tsconfig.json"

# --- Staleness check ------------------------------------------------------
needs_rebuild=false
if [ ! -f "${DASHBOARD_INDEX}" ]; then
  needs_rebuild=true
else
  # Build the path list dynamically so missing optional configs (e.g.
  # vite.config.ts on a stripped-down test fixture) don't make `find`
  # error out and falsely report "no newer files".
  paths=("${DASHBOARD_SRC}" "${DASHBOARD_PKG}")
  [ -f "${VITE_CONFIG}" ] && paths+=("${VITE_CONFIG}")
  [ -f "${TS_CONFIG}" ] && paths+=("${TS_CONFIG}")

  newer=$(find "${paths[@]}" \
    -type f \
    ! -path '*/node_modules/*' \
    ! -path '*/.git/*' \
    ! -name '.DS_Store' \
    ! -name '*~' \
    ! -name '*.swp' \
    ! -name '*.swo' \
    ! -name '.#*' \
    -newer "${DASHBOARD_INDEX}" -print -quit 2>/dev/null)
  if [ -n "$newer" ]; then
    needs_rebuild=true
  fi
fi

if [ "$needs_rebuild" = false ]; then
  exit 0
fi

# --- Rebuild --------------------------------------------------------------
# Dashboard depends on @oss-autopilot/core via workspace:* — npm cannot
# resolve that protocol, so without pnpm the build can't run. Surface the
# missing-tool case as a build failure with a clear remediation hint
# rather than letting npm explode mid-stream.
if ! command -v pnpm >/dev/null 2>&1; then
  echo "BUILD_FAILED: pnpm is required for the dashboard build (workspace:* dep). Install: npm install -g pnpm"
  exit 2
fi

remediation="cd ${PLUGIN_ROOT} && pnpm install && pnpm --filter @oss-autopilot/core run build && pnpm --filter @oss-autopilot/dashboard run build"
if (
  cd "${PLUGIN_ROOT}" &&
    pnpm install --silent &&
    pnpm --silent --filter @oss-autopilot/core run build &&
    pnpm --silent --filter @oss-autopilot/dashboard run build
) >&2; then
  exit 1
fi

echo "BUILD_FAILED: ${remediation}"
exit 2
